### ISSUE TITLE
Kodi 19 Matrix - Plugin not working

### ISSUE THREAD

**Issue by Agrajag-42** [hyperion-project/hyperion.control#14]
Just upgraded to Kodi 19 and the Plugin is not working anymore.

                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'iconImage' is an invalid keyword argument for this function
                                                   Traceback (most recent call last):
                                                     File "/var/lib/vdr/.kodi/addons/script.service.hypercon/default.py", line 110, in <module>
                                                       iconImage=defaultIcon)
                                                   TypeError: 'iconImage' is an invalid keyword argument for this function
                                                   -->End of Python script error report<--

**Comment by scr44tch** [comment]
i just tried to install it
The dependency on xbmc.python version 2.25.0 could not be satisfied

i think it needs to be updated for kodi 19

**Comment by derBernhard** [comment]
forked this git and modified it to work with Kodi 19. Works on Coreelec with Hyperion.ng

**Comment by scr44tch** [comment]
> forked this git and modified it to work with Kodi 19. Works on Coreelec with Hyperion.ng

working great thank you

**Comment by derBernhard** [comment]
Welcome

**Comment by Agrajag-42** [comment]
Is your Version made for Hyperion 2.0-NG?
For me it doesnt't work when i configure my Hyperion JSON Port under "Hyperion Webserver Port"

**Comment by tigertim08** [comment]
@derBernhard Vielen Dank für den fork 👍 Konnte ich ohne Probleme installieren. Allerdings bekomme ich mein Ambilight (Raspberry Zero W mit hyperion) nicht zum laufen. Mit dem alten Controller bzw. dem alten Kodi hat es funktioniert und auch über die Handyapp kann ich das Ambilight steuern. Port und IP habe ich selbstverständlich angepasst. 

Was muss ich denn bei Komponente eintragen?

Vielen Dank schonmal

**Comment by derBernhard** [comment]
Hm sorry, ich hab da echt nur ein paar Codezeilen angepasst, damit die aktuellen libs und so gezogen werden. Bei mir hat es allerdings mit hyperion auch nicht mehr funktioniert, weshalb ich auf hyperion.ng gewechselt habe. Wenn du einen log hast kann ich ja mal schaun ob ich was herausfinden kann.

**Comment by tigertim08** [comment]
> Hm sorry, ich hab da echt nur ein paar Codezeilen angepasst, damit die aktuellen libs und so gezogen werden. Bei mir hat es allerdings mit hyperion auch nicht mehr funktioniert, weshalb ich auf hyperion.ng gewechselt habe. Wenn du einen log hast kann ich ja mal schaun ob ich was herausfinden kann.

Danke, habe das log mal hochgeladen, selber hatte ich jetzt nichts gefunden... 

Wie hast du den umstieg auf hyperion.ng denn gemacht? Einfach drüber installiert oder komplett neu aufgesetzt?

[01_KODI.log](https://github.com/hyperion-project/hyperion.control/files/6195717/01_KODI.log)

**Comment by derBernhard** [comment]
Stimmt da sind keine Hyperion-Fehler drin. Vlt ein Config Problem. Schau dir mal die Komponente an und probier da mal durch. Ich kenn dein Setup nicht und weiß daher auch nicht wie das einzustellen ist. Bin da aber auch nicht der Richtige, weil ich den fork ja nur gemacht habe damits bei mir wieder läuft ;) Ansonsten gibts ja Foren zu Hauf wos genau um die Materie geht.

**Comment by Lord-Grey** [comment]
@derBernhard Maybe you would like to share your updates via a PR that everybody would benefit from it?
I would assume that the updated code would only work with Kodi 19+, correct?

Thank you!

**Comment by derBernhard** [comment]
hmm don't know so much about github.. I'm afraid of breaking something ;) Will try to do a PR.

**Comment by derBernhard** [comment]
ok. I did it ;) PR is done

**Comment by tigertim08** [comment]
@derBernhard Hey, habe jetzt auch mal mein hyperion auf dem pi zero auf .ng gehoben. Funktioniert auch soweit nur bekomme ich das Kodi Add-on nicht zum laufen also zum weiterleiten der Daten. Kannst du mir evtl. sagen wie du es bei dir eingestellt hast?

**Comment by WebSchw** [comment]
@derBernhard 
bei der Installation deines fork kommt es zum Fehler "[...] script.module.simplejson version 3.3.0 could not be satisfied [...]".
Ich nutze den neuesten Coreelec Release.

Davon ganz abgesehen. Wie stellt ihr Hyperion NG ein, damit es den Stream von dem Add-on nutzt?

**Comment by arfrater** [comment]
@derBernhard 
Hi I installed your version 19.01 and am getting these errors
`ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'dict' object has no attribute 'key'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.service.hyperion-control/service.py", line 221, in <module>
                                                       hyperion = Hyperion()
                                                     File "/storage/.kodi/addons/script.service.hyperion-control/service.py", line 91, in __init__
                                                       self.updateSettings()
                                                     File "/storage/.kodi/addons/script.service.hyperion-control/service.py", line 158, in updateSettings
                                                       self.connection.updateHeader(self.authToken)
                                                     File "/storage/.kodi/addons/script.service.hyperion-control/lib/connection.py", line 18, in updateHeader
                                                       elif not self.__headers.key('Authorization'):
                                                   AttributeError: 'dict' object has no attribute 'key'
                                                   -->End of Python script error report<--`

**Comment by xbmcnut** [comment]
@derBernhard Thank you so much for making this work with Matrix, much appreciated! Been loving 19 but missing my Hyperion.NG > WLED integration and this evening we're back online!

**Comment by xbmcnut** [comment]
@mind12 Sorry, which add-on are you wanting settings for as there was zero config required for the [Hyperion Control fork for Kodi 19](https://github.com/derBernhard/hyperion.control) add-on I added. I just detected my NG instance and started working.

**Comment by mind12** [comment]
> @mind12 Sorry, which add-on are you wanting settings for as there was zero config required for the [Hyperion Control fork for Kodi 19](https://github.com/derBernhard/hyperion.control) add-on I added. It just detected my NG instance and started working (once I updated the screen capture device).

Yeah this one, it doesnt work for me on Windows. I may try again. Any specific configuration that I need if HyperionNG is on another host?
